### ISSUE TITLE
Missing `pygobject` dependency on linux

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/msal_extensions-feedstock#10]
![image](https://user-images.githubusercontent.com/881019/115555973-7a725d00-a2f3-11eb-9848-7288231397d0.png)

* https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/Encryption-on-Linux

**Comment by dhirschfeld** [comment]
Without that dep I get the below error:
```
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
Runtime dependency of PyGObject is missing.
Depends on your Linux distro, you could install it system-wide by something like:
    sudo apt install python3-gi python3-gi-cairo gir1.2-secret-1
If necessary, please refer to PyGObject's doc:
https://pygobject.readthedocs.io/en/latest/getting_started.html
Traceback (most recent call last):
  File "/opt/conda/envs/quantdev/lib/python3.7/site-packages/msal_extensions/libsecret.py", line 21, in <module>
    import gi  # https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/Encryption-on-Linux
ModuleNotFoundError: No module named 'gi'
```

That's not the whole story though, as after installing [`pygobject`](https://github.com/conda-forge/pygobject-feedstock) I still see an error about `gir1.2-secret-1`:
```
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
Require a package "gir1.2-secret-1" which could be installed by:
        sudo apt install gir1.2-secret-1
        
Traceback (most recent call last):
  File "/opt/conda/envs/quantdev/lib/python3.7/site-packages/msal_extensions/libsecret.py", line 34, in <module>
    gi.require_version("Secret", "1")  # Would require a package gir1.2-secret-1
  File "/opt/conda/envs/quantdev/lib/python3.7/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available
```

**Comment by ianhelle** [comment]
We're seeing this same behavior on Azure Machine Learning computes.
Trying to use msal_extensions with an encrypted token cache fails:

- initially it fails with the `gi` dependency
- conda install pygobject fixes that but then fails on `gi.require_version("Secret", "1")
- installing gir1.2-secret-1 has no effect on this.
- manually installing gir1.2-secret-1 allows this to work in the system python3 but not in conda

Conda behavior
```
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:39:04) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version("Secret", "1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ian/anaconda3/envs/libsecret/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available
```

non-conda Python behavior
```
(libsecret) ian@IanHelle-dev2:/mnt/e/src$ conda deactivate
(base) ian@IanHelle-dev2:/mnt/e/src$ conda deactivate
ian@IanHelle-dev2:/mnt/e/src$ python3
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version("Secret", "1")
>>>
```

**Comment by dhirschfeld** [comment]
Does `conda install libsecret` fix the problem?

https://gitter.im/conda-forge/conda-forge.github.io?at=6080cadba9dd556843f296ae

**Comment by dhirschfeld** [comment]
> Does `conda install libsecret` fix the problem?

See also https://github.com/conda-forge/libsecret-feedstock/issues/6#issuecomment-1152284781

**Comment by dhirschfeld** [comment]
If this issue is still being observed after #23, it can always be reopened...
